apiVersion: apps/v1
kind: Deployment
metadata:
  name: manideployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
spec:
  replicas: 1 #The number of pods to be created in the Kubernetes cluster for the mani-java-app application container
  template:
    metadata:
    spec:
      containers:
      - name: mani-java-app #The name of the mani-java-app application container
        image: manindertiet/maniprivaterepo:latest #The Docker image for building the mani-java-app application container
        ports:
        - containerPort: 3000 #The port for the mani-java-app application container
