apiVersion: v1
kind: Service
metadata:
  labels:
    app: mani-java-app
  name: maniservice #The name of the Kubernetes Service to be created in the Kubernetes cluster
  namespace: devops-tools
spec:
  selector:
    app: mani-java-app 
  type: ClusterIP #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 3000 #Service port
    targetPort: 3000 #The port for the mani-java-app application container
